[package]
name = "datasize_derive"
version = "0.1.0"
authors = ["Marc Brinkmann <marc@casperlabs.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.21"
quote = "1.0.7"
syn = { version = "1.0.41", features = ["full", "extra-traits"] }
